// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApi.Data;

#nullable disable

namespace RestApi.Migrations
{
    [DbContext(typeof(RestApiDbContext))]
    [Migration("20260122153632_links")]
    partial class links
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestApi.Models.Intrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Intrests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Att ta och redigera bilder.",
                            Name = "Fotografi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Träning och tävling inom långdistans.",
                            Name = "Löpning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Experimentera med recept och råvaror.",
                            Name = "Matlagning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spela spel på PC och konsol.",
                            Name = "Gaming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Utforska nya platser och kulturer.",
                            Name = "Resor"
                        });
                });

            modelBuilder.Entity("RestApi.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntrestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntrestId");

                    b.HasIndex("PersonId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("RestApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.svensson@example.com",
                            FirstName = "Anna",
                            LastName = "Svensson",
                            PhoneNr = "0701234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "johan.lindberg@example.com",
                            FirstName = "Johan",
                            LastName = "Lindberg",
                            PhoneNr = "0739876543"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sara.ekstrom@example.com",
                            FirstName = "Sara",
                            LastName = "Ekström",
                            PhoneNr = "0765551122"
                        },
                        new
                        {
                            Id = 4,
                            Email = "daniel.hultmark@example.com",
                            FirstName = "Daniel",
                            LastName = "Hultmark",
                            PhoneNr = "0707654321"
                        },
                        new
                        {
                            Id = 5,
                            Email = "mikael.berg@example.com",
                            FirstName = "Mikael",
                            LastName = "Berg",
                            PhoneNr = "0729988776"
                        });
                });

            modelBuilder.Entity("RestApi.Models.PersonIntrest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IntrestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntrestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonIntrests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IntrestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            IntrestId = 3,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            IntrestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            IntrestId = 5,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 5,
                            IntrestId = 4,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 6,
                            IntrestId = 1,
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("RestApi.Models.Link", b =>
                {
                    b.HasOne("RestApi.Models.Intrest", "Intrest")
                        .WithMany()
                        .HasForeignKey("IntrestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestApi.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intrest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RestApi.Models.PersonIntrest", b =>
                {
                    b.HasOne("RestApi.Models.Intrest", "Intrest")
                        .WithMany()
                        .HasForeignKey("IntrestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestApi.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intrest");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
